data/videos.xml
previous link was broken, since a recent server update
=> link to slides updated

modules/search.xql
not just the first hit in the search context
=> output all hits in hit-list

modules/search.xql, resources/css/doc.css, search.html
also: fixing size of dropdowns and changing "One Line" to "Concordance"
=> defaulting to kwic (concordance) hit-list

data/production_web_proxying.xml
Fixing major documentation issue that resulted in broken sessions, some minor improvements.
More details: http://markmail.org/message/amfor3i5f3snhb6a
=> Fix web proxy documentation

data/lucene.xml
Update example code for lucene 4
=> Correct qualified name of Whitespace-Analyzer

build.xml, data/lucene.xml, data/urlrewrite.xml
* Lucene configuration for different versions.
* Attribute boosting
* Other minor proofings.
=> Some more changes to documentation for eXist-db 3.0. Bumping version.

data/repo.xml
issue raised on mailing list on Feb 10, 2016: http://markmail.org/message/b65722t7s73fcpvo
=> supply namespace declaration for code snippet

data/xsl-transform.xml
these were missing for quite some time.
=> added description of xslt/transform 4th and 5th parameter

data/newrangeindex.xml
=> Typo and accidentally a word

data/upgrading.xml
see eXist-db/documentation#86, eXist-db/documentation#69
=> incorporate upgrade info from JLO's blog post.

.gitignore, data/development-starter.xml, data/indexing.xml, data/repo.xml
updated references that assumed 2.2 as latest to 3.0
=> make 3.0 current

.gitignore, data/quickstart.xml
see eXist-db/eXist#1274, eXist-db/eXist#1275, eXist-db/eXist#1248
=> MacOS quicker start

data/lucene.xml
Fix WhitespaceAnalyzer package and link to correct version of Lucene
=> Small fixes

data/newrangeindex.xml
Add documentation for range index condition features implemented in exist-db/exist#1252
=> Range index conditions

data/troubleshooting.xml
closes eXist-db/documentation#110
=> added path to .app for macOS, fixed dead link to JAVA_HOME how to

data/troubleshooting.xml
=> fixed Typo

data/production_web_proxying.xml
relates to https://github.com/eXist-db/exist/issues/1442
=> Adds a note about the impossibility to alias WebDAV w/ a proxy

data/deployment.xml, data/troubleshooting.xml
Updated instructions on file locations for server port and application context
=> Modify root url instructions

data/triggers.xml
See: https://github.com/eXist-db/exist/issues/1547#issuecomment-329523461
=> Only use collection.xconf

data/indexing.xml
Closes https://github.com/eXist-db/exist/issues/1282
=> Collection configuration MUST be collection.xconf

data/devguide.xml
I removed the sentence about XMLDBTransformer because there is no doc page about it anymore.
=> XMLDBTransformer is deprecated

README.md, RELEASE.md, pom.xml, src/changes/changes.xml, src/main/xar-resources/data/upgrading.xml, xar-assembly.xml
This should cover my action ticket.
There should be more about releases that we can mavenize, but i ll leave that to people more familiar with maven to achieve it.
=> Readme and release changes

src/main/xar-resources/data/configuration.xml
addresses a number of open issues regarding the configuration.xml article
=> Address issues regarding the configuration.xml article

src/main/xar-resources/data/production_good_practice.xml
=> add info on hardening production systems

.gitignore, RELEASE.md, pom.xml
also added change report to gitignore in case it gets created in project dir
=> point back to target

pom.xml
so we use the latest kuberam for building expath package
=> update app-parent version

src/main/xar-resources/data/contentextraction.xml
I only found one mention.
see eXist-db/exist#1708
=> fix empty-sequence in example

pom.xml, src/main/xar-resources/data/author-reference/author-reference.xml, src/main/xar-resources/data/deployment/deployment.xml, src/main/xar-resources/data/incompatibilities/incompatibilities.xml
maven dependancy update
add Dashboard warning to incompatibilities
fix typo in author guide
close #210
=> add Jetty portal folder info to deplyoment

src/main/xar-resources/data/deployment/deployment.xml, src/main/xar-resources/data/xforms/xforms.xml
some small updates to the betterFORM parts of the document.
=> reviewed betterFORM information

src/main/xar-resources/modules/search.xql
This is untested, but should be cleaner (assuming it works)
=> Improve filter for q=xsl

src/main/xar-resources/data/advanced-installation/advanced-installation.xml
=> [style fix] on adv-installation.xml

src/main/xar-resources/data/xqsuite/listings/listing-8.xml, src/main/xar-resources/data/xqsuite/xqsuite.xml
See https://github.com/eXist-db/exist/pull/1978#issuecomment-401297630
=> explain pending & error counts in testsuite

src/main/xar-resources/data/basic-installation/basic-installation.xml
as per community call A-180827-2
=> more emphatically support openJDK

src/main/xar-resources/data/xqsuite/xqsuite.xml
noticed that this wasn't mentioned in the docs
=> add info about %test:name to xqsuite article

src/main/xar-resources/data/lucene/listings/listing-10.txt, src/main/xar-resources/data/lucene/listings/listing-15.txt, src/main/xar-resources/data/lucene/listings/listing-16.txt, src/main/xar-resources/data/lucene/listings/listing-17.txt, src/main/xar-resources/data/lucene/listings/listing-18.txt, src/main/xar-resources/data/lucene/listings/listing-21.txt, src/main/xar-resources/data/lucene/listings/listing-26.txt, src/main/xar-resources/data/lucene/listings/listing-27.xml, src/main/xar-resources/data/lucene/listings/listing-28.xml, src/main/xar-resources/data/lucene/listings/listing-33.txt, src/main/xar-resources/data/lucene/lucene.xml, src/main/xar-resources/data/webdav/listings/listing-2.txt, src/main/xar-resources/data/webdav/webdav.xml
webdav wasn't rendering correctly, trimmed some rhetorical fat while I was at it. 
some rewording to to lucene
=> Style fixes

src/main/xar-resources/data/integration-testing/integration-testing.xml, src/main/xar-resources/data/integration-testing/listings/travis-1.txt, src/main/xar-resources/data/integration-testing/listings/travis-2.txt, src/main/xar-resources/data/testing/testing.xml
Minor fixes to typos, spelling, style, etc.
@duncdrum Kudos on these new articles - they're great and really helpful!
=> Review testing articles

.travis.yml
=> ci(travis): point to slack instead of hipchat

src/main/xar-resources/data/extensions/extensions.xml
=> fix(xprocq): remove mentions of xprocq

src/main/xar-resources/data/xquery/xquery.xml
See https://github.com/eXist-db/exist/commit/76c6fd9f244cf47d123a0be5c38c4b8c9b8fbc4a.
=> fn:random-number-generator#0, #1 was added

src/main/xar-resources/modules/docbook.xql, src/main/xar-resources/modules/view.xql
=> Fix map constructor syntax

src/main/xar-resources/data/configuration/configuration.xml, src/main/xar-resources/data/production_good_practice/production_good_practice.xml
Closes https://github.com/eXist-db/documentation/issues/377
See PR - https://github.com/eXist-db/exist/pull/2962
=> Add some detail about disabling the Lock Table

src/main/xar-resources/data/development-starter/development-starter.xml
Getting rid of the `spacing="compact"` should fix the problem like it did in #383
=> Fixes #388

src/main/xar-resources/data/repo/repo.xml
See https://github.com/eXist-db/public-repo/pull/48. Revised code sample depends upon https://github.com/eXist-db/public-repo/pull/48 being merged and the revised public-repo app being installed on exist-db.org.
=> Fix public-repo find endpoint

src/main/xar-resources/data/lucene/listings/listing-1.txt, src/main/xar-resources/data/lucene/lucene.xml
=> feat(lucene): add min attribute for boolean query

src/main/xar-resources/data/xquery/xquery.xml
updated documentation for pull request 3092 ( https://github.com/eXist-db/exist/pull/3092 )
=> doc: remove array:put from unsupported functions

src/main/xar-resources/data/lucene/listings/listing-520.xml, src/main/xar-resources/data/lucene/listings/listing-521.txt, src/main/xar-resources/data/lucene/listings/listing-522.xml, src/main/xar-resources/data/lucene/lucene.xml
accompanying https://github.com/eXist-db/exist/pull/3182
=> (feature) multi-value hierarchical facets documentation

src/main/xar-resources/data/lucene/listings/listing-571.txt, src/main/xar-resources/data/lucene/lucene.xml
particularly explaining nuances of hierarchical facets and multiple values
accompanying https://github.com/eXist-db/exist/pull/3182
=> (feature) detailed explanation of refining queries with facets

src/main/xar-resources/data/lucene/listings/listing-48.txt, src/main/xar-resources/data/lucene/lucene.xml
Documenting the feature of PR#2991
and fixing some typos in other parts of the doc
=> Docs PR# 2991 - Distinct Lucene analyzers for indexing and querying

src/main/xar-resources/data/scheduler/scheduler.xml
Closes https://github.com/eXist-db/documentation/issues/456
=> Fix link to Quartz documentation

src/main/xar-resources/data/exist-building/exist-building.xml
This adds details of build profiles and how to enable/disable them.
=> Document build profiles

src/main/xar-resources/data/kwic/kwic.xml, src/main/xar-resources/data/lucene/listings/listing-60.txt, src/main/xar-resources/data/lucene/lucene.xml
accompanying https://github.com/eXist-db/exist/pull/3423
=> Documentation for ft:highlight-field-matches

src/main/xar-resources/data/xquery/xquery.xml
Thanks to @dizzzz's https://github.com/eXist-db/exist/pull/3597
=> fn:trace#1 is now supported

src/main/xar-resources/data/xquery/xquery.xml
Thanks to @adamretter's https://github.com/eXist-db/exist/pull/3596
=> array:sort is now supported

src/main/xar-resources/data/newrangeindex/listings/listing-13.txt, src/main/xar-resources/data/newrangeindex/listings/listing-5.xml, src/main/xar-resources/data/newrangeindex/listings/listing-6.txt, src/main/xar-resources/data/newrangeindex/listings/listing-8.txt, src/main/xar-resources/data/newrangeindex/newrangeindex.xml
=> Update new rangeindex txt a bit

src/main/xar-resources/data/backup/backup.xml
This fixes a broken link in the documentation.
=> Update link, as latest was broken

src/main/xar-resources/data/exist-building/exist-building.xml
Add a doc of build option for working offline with Xars
=> Add offline mode for Xars

src/main/xar-resources/data/development-starter/development-starter.xml, src/main/xar-resources/data/templating/listings/listing-12.txt, src/main/xar-resources/data/templating/templating.xml, src/main/xar-resources/data/urlrewrite/urlrewrite.xml
Documentation for https://github.com/eXist-db/exist/pull/3757
=> URL Rewrite should now use controller.xq and not controller.xql

src/main/xar-resources/data/configuration/configuration.xml, src/main/xar-resources/data/extensions/extensions.xml, src/main/xar-resources/data/extensions/listings/listing-1.xml
Related to https://github.com/eXist-db/exist/pull/3831
=> Some documentation for Connection Pooling in the SQL Module

src/main/xar-resources/data/templating/listings/listing-12.txt, src/main/xar-resources/data/templating/listings/listing-14.xml, src/main/xar-resources/data/templating/listings/listing-15.txt, src/main/xar-resources/data/templating/listings/listing-16.txt, src/main/xar-resources/data/templating/templating.xml
* align with new templating package 
* document upgrade path
* mark deprecated/removed functions
=> Review documentation on HTML templating

README.md, package-lock.json, package.json, pom.xml, src/main/xar-resources/data/production_good_practice/production_good_practice.xml, xar-assembly.xml
changed scm.connection|developerConnection|url to scm:git:https://github.com cause de.jutzig github-release-plugin fails otherwise
=> changed scm urls cause de.jutzig github-release-plugin falis otherwise

src/main/xar-resources/data/xquery/listings/listing-40.txt, src/main/xar-resources/data/xquery/listings/listing-41.txt, src/main/xar-resources/data/xquery/listings/listing-42.txt, src/main/xar-resources/data/xquery/listings/listing-43.txt, src/main/xar-resources/data/xquery/listings/listing-44.txt, src/main/xar-resources/data/xquery/listings/listing-45.txt, src/main/xar-resources/data/xquery/xquery.xml
Documentation for https://github.com/eXist-db/exist/pull/3990
=> doc(xquery.xml): add in-built function map options

src/main/xar-resources/data/advanced-installation/advanced-installation.xml
refs https://github.com/eXist-db/exist/pull/4196
=> [enhancement] document startup flags

src/main/xar-resources/data/kwic/listings/listing-5.txt, src/main/xar-resources/data/kwic/listings/listing-6.txt, src/main/xar-resources/data/kwic/listings/listing-7.txt
closes #751
refs https://github.com/eXist-db/exist/issues/4239
=> [enhancement] update KWIC listing

src/main/xar-resources/data/triggers/triggers.xml
As requested by @line-o for https://github.com/eXist-db/exist/pull/4280
=> Add a note that it is possible to chain XQuery Triggers together

src/main/xar-resources/data/xqsuite/listings/assertion-lib.txt, src/main/xar-resources/data/xqsuite/listings/custom-assertion-fallback.txt, src/main/xar-resources/data/xqsuite/listings/custom-assertion-result.xml, src/main/xar-resources/data/xqsuite/listings/custom-assertion.txt, src/main/xar-resources/data/xqsuite/listings/minimal-example.txt, src/main/xar-resources/data/xqsuite/xqsuite.xml
Document how to use custom assertions including fallback for backwards compatibility.
=> [enhance] xqsuite with custom assertions

src/main/xar-resources/data/lucene/listings/listing-54.txt, src/main/xar-resources/data/lucene/listings/listing-55.txt, src/main/xar-resources/data/lucene/listings/listing-581.xml, src/main/xar-resources/data/lucene/lucene.xml
To be merged when https://github.com/eXist-db/exist/pull/4253 is ready
=> Document newly added lucene binary fields

src/main/xar-resources/data/xquery/xquery.xml
* Add output-doctype exist serialization option
* options are not boolean but actually "yes" | "no" values
=> Add output-doctype exist serialization option

src/main/xar-resources/modules/view.xql
Closes https://github.com/eXist-db/documentation/issues/903
=> Make compatible with eXist-db 7.x.x
