eXist-db/documentation

data/devguide_xmlrpc.xml
For the Perl examples, added a {} to execute request.
Also, used quotes to make xquery expressions easier to read.
issue #756
=> Fix Perl XML-RPC example

data/advanced-installation.xml
Using "server" instead of "standalone" gives
a "java.lang.ClassNotFoundException: server" error.
=> Fix for command to launch eXist as stand-alone server process.

data/production_good_practice.xml
I have just corrected this part where it was written the default permissions in eXist for /db are 0777, which is not true. It should be 0755.
=> Update for /db permissions part in the documentation

data/newrangeindex.xml
Describes how to use conditions for complex range index config elements supported by the current eXist 3.0 code base (as introduced in exist-db/exist#1233). 
I will extend this accordingly when exist-db/exist#1252 gets merged...
=> Add initial information about range index conditions

data/lucene.xml, modules/docbook.xql
Description of 'xref' element: http://docbook.org/tdg5/en/html/xref.html.
This element makes easier to maintain the pages, compared to 'ulink' element, as the content of the generated HTML 'a' element is generated automatically from the text content of the 'title' child element of the referenced element (which can be, for instance, a 'section' element).
=> Added support for processing the 'xref' elements

data/advanced-installation.xml, data/quickstart.xml, data/troubleshooting.xml, data/upgrading.xml, data/uploading-files.xml, data/webdav.xml
Since 2016  “Mac OS X” is now macOS. Please squash or rebase on merge.
=> macOS name fix

.gitignore, README.md, build.properties, build.xml, expath-pkg.xml.tmpl, repo.xml
As proposed in #96:
- Adopt conventions for app name and version properties
- Add release notes describing which articles had improvements and what those improvements were (drawn from commit history) so users know what to look out for
- Add github repo as repo website link
- Revise note shown during upgrade to indicate it is only a concern for eXist 2.x users
- Improve README
=> Prepare v0.4.8

data/backup.xml
Also, at the same page exist/apps/doc/build/doc-0.4.8/backup.xml at the paragraph 
>**Scheduling Backups and Consistency Checks**
>The core class for the server-side backup as well as consistency checks is called ConsistencyCheckTask. It can be registered as a system task with eXist-db's scheduler. 
Link with the text _scheduler_ has wrong anchor
http://localhost:8888/exist/apps/doc/build/doc-0.4.8/configuration.xml#N104CF
=> Fixed external link to cron trigger site and one internal link

data/devguide_soap.xml, data/devguide_xmldb.xml, data/devguide_xmlrpc.xml, data/xquery.xml
I don't know if javadocs for exist api are supposed to be a part of the Documentation app, but at this point it is not a case. So I have changed those broken relative links with the absolute ones that point to the online version of the api javadocs.
=> Changed broken relative javadocs links with absolute ones

pom.xml, src/main/xar-resources/data/backup.xml, src/main/xar-resources/data/incompatibilities.xml, src/main/xar-resources/data/upgrading.xml
and backup instructions
release notes on blog incomplete hence the new incompatibilities article
bumped version in pom to 3.0.0
closes #120, see #142
=> further tweaks to upgrading

ISSUE_TEMPLATE.md, src/main/xar-resources/data/extensions/extensions.xml, src/main/xar-resources/data/incompatibilities/incompatibilities.xml, src/main/xar-resources/data/templating/listings/listing-8.txt
increase issue template default version
fix dangling reference expanders close #180, #182
switch to new map syntax in listings (not yet in app code) close #189
=> minor fixes

src/main/xar-resources/data/advanced-installation/advanced-installation.xml
Updated the section of the Advanced Installation instruction that describe the use of YAJSW. Specifically rewrote the description of the the key configurations available with YAJSW to include the ping timeout variable.
=> Update advanced installation - better intro to YAJSW configs

README.md
this should be merged as soon as version 4.0.0 of the docs is live on exist-db.org aka when they use exist 4.0.0 
closes exist-db/documentation#184
=> add link to style guide 

src/main/xar-resources/data/basic-installation/basic-installation.xml, src/main/xar-resources/data/exist-building/exist-building.xml
make it easier for folks to find the build instructions, when browsing the docs. 
see #251
see eXist-db/exist#1933
=> add build links

src/main/xar-resources/data/configuration/listings/listing-4.xml
The previous sample still referenced the ft-legacy-index as follows: “is always required and should not be disabled”. It also showed caseSensitive=“no”, which the docs describe as “a dirty workaround, which will be removed in the future.” Better to use the default conf.xml with current, recommended settings.
=> Copy <indexer> from current conf.xml

.travis.yml, src/main/xar-resources/data/lucene/lucene.xml, src/main/xar-resources/data/xqsuite/xqsuite.xml
bump oracleJDK to 11 its LTS, and 9 is EOL
some typos
close #270
=> Travis patch

src/main/xar-resources/data/advanced-installation/advanced-installation.xml
This PR adds a section to the documentation describing how to set up a system for unattended installation. original use case was a customized and packaged version of eXist within a debian package container that offers a post installation stage where one can call the `installDaemon.sh` script. For automatic deployment the scenario is of course an unattended installation.
=> documentation regarding eXist-db/exist#2239

src/main/xar-resources/data/production_good_practice/listings/listing-3.xml, src/main/xar-resources/data/production_good_practice/production_good_practice.xml
I've added the
```
<feature name="http://xml.org/sax/features/external-general-entities" value="false"/>
<feature name="http://xml.org/sax/features/external-parameter-entities" value="false"/>
<feature name="http://javax.xml.XMLConstants/feature/secure-processing" value="true"/>
```
instruction to the `<parser>` section.
=> Add parser paragraph

pom.xml
turns out maven isn't all bad; bump npm version via pom, 
todo: i think the `package.json` should find its way into the xar package but thats a battle for another day
=> fix(review): bump semver in packag.json from pom.xml

src/main/xar-resources/data/upgrading/upgrading.xml
As requested in https://github.com/eXist-db/exist/pull/2351#issuecomment-447631464
=> Note on upgrading 2.2 and earlier to eXist-db 5.0.0+

src/main/xar-resources/data/extensions/extensions.xml, src/main/xar-resources/data/security/security.xml, src/main/xar-resources/data/xquery/xquery.xml
removes mentions of soon to be deprecated stuff. 
see eXist-db/exist#2603
=> fix(extensions): remove deprecated extensions

src/main/xar-resources/data/xquery/xquery.xml
update documentation for https://github.com/eXist-db/exist/pull/2857
=> doc: remove fn:parse-ietf-date from unsupported functions

src/main/xar-resources/data/devguide_indexes/devguide_indexes.xml
This element:
```
<para>
<literal>repair()</literal> reconstructs every index (including the structural one) from what is contained in the persistent DOM (usually <literal>dom.dbx</literal>).
</para>
```
was appearing twice. I just kept the first occurrence of it.
=> Removed duplicated <para>

src/main/xar-resources/data/configuration/configuration.xml
=> Add a small section on experimental document path-locks

src/main/xar-resources/data/xquery/xquery.xml
Update documentation for https://github.com/eXist-db/exist/pull/3141
=> doc: remove fn:xml-to-json#1, #2 from unsupported functions

src/main/xar-resources/data/xquery/xquery.xml
Just a minor update. The legacy map constructor syntax was removed in https://github.com/eXist-db/exist/pull/2890.
=> Old map constructor syntax was removed in 5.0.0

src/main/xar-resources/data/oxygen/oxygen.xml
The Preferences dialogue has changed within latest version of Oxygen and the steps were incorrect concerning setting up validation against the eXist-db engine
=> updated validating against eXist-db XQuery engine

src/main/xar-resources/data/backup/backup.xml, src/main/xar-resources/data/backup/listings/listing-12.txt, src/main/xar-resources/data/backup/listings/listing-7.txt
Add a short paragraph documenting the use of `--use-ssl` for the backup client (see <https://github.com/eXist-db/exist/issues/3434>).
=> Add documentation for backup client flag --use-ssl

src/main/xar-resources/data/integration-testing/integration-testing.xml, src/main/xar-resources/data/integration-testing/listings/travis-1.txt, src/main/xar-resources/data/integration-testing/listings/travis-2.txt, src/main/xar-resources/data/integration-testing/listings/travis-3.txt, src/main/xar-resources/data/integration-testing/listings/travis-4.txt
fix typo
fix highlighting
close #521
=> fix(int-test): update listings

src/main/xar-resources/data/xquery/xquery.xml
The FLWOR expression's `allowing empty` keywords (see [spec](https://www.w3.org/TR/xquery-31/#id-xquery-for-clause)) have been actually been supported since https://github.com/eXist-db/exist/pull/763 (commit https://github.com/eXist-db/exist/commit/b0e9eb5faa20374c4460bd7ada23464c78e02d2c), released with eXist 3.0.
=> Update xquery.xml - allowing empty

src/main/xar-resources/data/exist-building/exist-building.xml
Adds a line to the build configuration options, with `-Ddocker.tag` as it is really useful to distinguish your builds from the official ones.
=> Add -Ddocker.tag to documentation

src/main/xar-resources/data/newrangeindex/newrangeindex.xml
This adds a pointer to range:matches as an alternative to fn:matches with the new range index (subject to Lucene limitation). 
Possible improvement that was beyond my ability: I copied the pointer to the Lucene documentation from some earlier eXist-db documentation, but the Lucene page in question is written for Java developers, and it is not likely to be intelligible to eXist-db users who need to know, without formal grammar productions or Java code, which common regex features cannot be used with the new range index. I was not able to find a clear statement of this in plain language either on the eXist-db site or in any Lucene documentation, and I was not confident about whether I understood the limitations well enough to write it myself. Might someone who knows the details be able to …
=> Add pointer to range:matches in documentation of new range index

pom.xml, xar-assembly.xml
@joewiz This is the missing commit that we discussed on the call this evening.
Actually two commits now, as I later found a problem (via these integration tests) with the docs declaring a dependency on `shared-resources` 0.8.2. It turns out that shared-resources 0.8.2 is not compatible with eXist-db 5.x.x due to its use of old style Map syntax, so I bumped the version of the dependency to 0.8.4.
=> Test built package in Integration Test

cypress.json
the link on the readme takes you to the old dashboard, which is part of our the FOSS plan cypress has granted the exist-db org, there was no need to open a new org, and we should keep the history of runs on the same dashboard.
=> fix(cypress): revert new projectID

pom.xml
introduced by 3b49f4f77438ed01ab7d9bc6ab07ba99e3bf19e1
secret sharing of record key is not a thing
close #631
```
.
.
. ;.
.;
;;.
;.;;
;;;;.
;;;;;
;;;;;
;;;;;
;;;;;
;;;;;
..;;;;;..
':::::'
':`
```
=> fix(pom): failing tests on CI for PRs

.gitignore, Gulpfile.js, xar-assembly.xml
In the end an easy fix, the behaviour is already supported by the `kuberam-expath-plugin`.
Closes https://github.com/eXist-db/documentation/issues/633
=> Generated resources should go into target dir and not src dir

package-lock.json, package.json, pom.xml, src/test/cypress/integration/documentation_spec.js
Closes https://github.com/eXist-db/documentation/issues/629
=> Update to Node 14

pom.xml
force mvn release plugin to use credentials from .m2/settings.xml  >  server.id = github
=> force mvn release plugin to use credentials from .m2/settings.xml 

.github/config.yml
To a user who has just submitted their first issue, the phrase "Be sure to follow the issue template!" reads as if the user failed to follow the template.
=> Remove phrase from 1st issue thank you template which suggests the user erred

src/main/xar-resources/data/lucene/listings/listing-311.xml, src/main/xar-resources/data/lucene/lucene.xml
Counterpart to https://github.com/eXist-db/exist/pull/4082.
=> Improve custom analyzer config

src/main/xar-resources/data/java-admin-client/java-admin-client.xml
Without specifying the target collection using the `-c` or `--collection` argument, the command will fail with an appropriate error message. Thus, if the target collection is mandatory, it should be included in the examples.
=> Update java-admin-client.xml - fix store command

src/main/xar-resources/data/xquery/listings/listing-40.txt, src/main/xar-resources/data/xquery/listings/listing-41.txt, src/main/xar-resources/data/xquery/listings/listing-42.txt, src/main/xar-resources/data/xquery/listings/listing-43.txt, src/main/xar-resources/data/xquery/listings/listing-44.txt, src/main/xar-resources/data/xquery/listings/listing-45.txt, src/main/xar-resources/data/xquery/listings/listing-46.txt, src/main/xar-resources/data/xquery/xquery.xml
- separate existdb specific options into extensions and legacy / deprecated options 
- remove unnecessary QName from fn:serialize listings
- add new parameter `insert-final-newline`
=> [doc] expand Xquery serialization section

src/main/xar-resources/data/lucene/listings/listing-48.txt, src/main/xar-resources/data/lucene/lucene.xml
Fixes #447 
this PR document the feature add in https://github.com/eXist-db/exist/pull/1378
the wording used for it:
**`lowercase-expanded-terms `**
```
Key used to set whether expanded terms should be lower-cased, LOWERCASE_EXPANDED_TERMS 
when set to yes automatically lowercases wildcard, regex and fuzzy queries.
Default value is no.
```
This open source contribution to the [exist-documentation](https://github.com/eXist-db/documentation) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
=> add lowercase-expended-term

src/main/xar-resources/data/xquery/xquery.xml
after the discussion in https://github.com/eXist-db/documentation/issues/436
@adamretter has suggested 
`I think it would be best to remove the list of unsupported serialization parameters from the page as this issue originally suggested. If necessary, we could add a sentence about there being possible bugs, as full XQTS compliance has yet to be reached` 
i updated the unsupported features section to
```
eXist-db does supports all standard serialization 
parameters but there is possible bugs, 
as full XQTS compliance has yet to be reached.
```
This open source contribution to the [exist-documentation](https://github.com/eXist-db/documentation) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
=> state the standard serialization params as unstable 

src/main/xar-resources/data/repo/repo.xml
The EXPath Package spec does not mention icon.png, but if the eXist-db Dashboard finds an image resource with a filename beginning with the string "icon" in the root directory of an app, it will display that instead of the default eXist-db blue dotted "X". See https://markmail.org/message/5m6fjqso4m4veuos
=> Document icon.png

src/main/xar-resources/data/xquery/xquery.xml
- fn:default-language - added in https://github.com/eXist-db/exist/pull/4360
- fn:document-uri - added in https://github.com/eXist-db/exist/pull/3644
- fn:format-integer - added in https://github.com/eXist-db/exist/pull/4366
- fn:map-merge#2 - added in https://github.com/eXist-db/exist/pull/4002 (note: spec-compliant version is pending merge of https://github.com/eXist-db/exist/pull/3738 in a forthcoming major version of eXist)
**Update (2023-01-03):**
- xs:dateTimeStamp - added in https://github.com/eXist-db/exist/pull/4393
- fn:round - added in https://github.com/eXist-db/exist/pull/4400
- map:find - added in https://github.com/eXist-db/exist/pull/4401
- fn:path - added in https://github.com/eXist-db/exist/pull/4402
- fn:nilled - added in https://github.com/eXist-db/exist/pull/4405
- …
=> Account for recently added XQuery 3.1 functions

src/main/xar-resources/data/jmx/jmx.xml
This PR addresses incomplete instruction on JMX access over HTTP that could lead to misapprehensions about the security of the service.
fixes #106 
This open source contribution to the eXist-db project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
=> JMX access over HTTP clarification

src/main/xar-resources/data/xqsuite/xqsuite.xml
... and document the inclusion of support for default namespaces added in https://github.com/eXist-db/exist/pull/4799.
=> [xqsuite] Flesh out docs for %test:assertXPath annotation

src/main/xar-resources/data/urlrewrite/listings/listing-1.txt, src/main/xar-resources/data/urlrewrite/listings/listing-10.txt, src/main/xar-resources/data/urlrewrite/listings/listing-11.txt, src/main/xar-resources/data/urlrewrite/listings/listing-12.txt, src/main/xar-resources/data/urlrewrite/listings/listing-2.txt, src/main/xar-resources/data/urlrewrite/urlrewrite.xml, src/main/xar-resources/modules/xsl/convert-db5.xsl
Closes #200 .
This PR uses @wolfgangmm #227  for the URL Rewriting and all the fixes in that Pr.
It removes outdated parts, rename all `xql` to `xq`.
This open source contribution to the [documentation](https://github.com/eXist-db/documentation) project was commissioned by the Office of the Historian, U.S. Department of State, https://history.state.gov/.
=> URL Rewriting

src/main/xar-resources/data/urlrewrite/listings/listing-14.xml, src/main/xar-resources/data/urlrewrite/listings/listing-15.xml, src/main/xar-resources/data/urlrewrite/listings/listing-16.xml, src/main/xar-resources/data/urlrewrite/listings/listing-17.xml, src/main/xar-resources/data/urlrewrite/listings/listing-18.xml, src/main/xar-resources/data/urlrewrite/listings/listing-19.xml, src/main/xar-resources/data/urlrewrite/listings/listing-20.xml, src/main/xar-resources/data/urlrewrite/listings/listing-21.xml, src/main/xar-resources/data/urlrewrite/urlrewrite.xml
=> Move inline programlistings into includes

src/main/xar-resources/data/urlrewrite/listings/listing-1.txt, src/main/xar-resources/data/urlrewrite/listings/listing-11.txt, src/main/xar-resources/data/urlrewrite/listings/listing-19.xml, src/main/xar-resources/data/urlrewrite/listings/listing-2.txt, src/main/xar-resources/data/urlrewrite/listings/listing-22.xml, src/main/xar-resources/data/urlrewrite/listings/listing-3.txt, src/main/xar-resources/data/urlrewrite/listings/listing-7.txt, src/main/xar-resources/data/urlrewrite/urlrewrite.xml
- the /tools root is no longer in eXist
- the sandbox tool is no longer in eXist; adapted to discuss eXide
- added a few essential details to the picture of URL processing and controller-config
- incorporate recent changes to roots in https://github.com/eXist-db/exist/pull/4807
- reorder $exist:* variables from most general to most specific components
- add descriptions of common uses of URL rewriting
=> [urlrewrite] Minor edits

src/main/xar-resources/data/configuration/configuration.xml
Corresponds to https://github.com/eXist-db/exist/pull/5195 and 6.x backport https://github.com/eXist-db/exist/pull/5217.
=> Added documentation for content file pool

src/main/xar-resources/data/xquery/xquery.xml
=> Add exist:profiling pragma

pom.xml, src/main/xar-resources/modules/view.xql, src/main/xar-resources/search.html
Depend on upcoming templating v1.2.0 and make use of its new capabilities.
- Rendered HTML will no longer be cluttered with `data-template` attributes.
- Legacy class-syntax for templates is no longer allowed
- various smaller improvements
=> Refactor view module

Gulpfile.js, package.json, src/main/frontend/sass/_layout.scss, src/main/xar-resources/modules/view.xql
- correct output options
- condense rendered HTML
- improve CSSprefixer configuration
- minor improvement in header layout
=> Minor improvements

src/main/xar-resources/data/templating/listings/listing-12.txt, src/main/xar-resources/data/templating/listings/listing-13.txt, src/main/xar-resources/data/templating/listings/listing-7.xml, src/main/xar-resources/data/templating/templating.xml
fixes #1136
fixes #247
Changes listings and adds a paragraph explaining the legacy syntax, why it was changed and how to configure to ignore it.
=> doc(templating): add legacy syntax, update examples
